name: Storybook VRT
on:
  deployment_status:
jobs:
  playwright:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    name: 'Storybook VRT'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Screenshot for Production
        run: npm run storybook:vrt:update
        env:
          BASE_URL: https://tech-vinyl.jp/
      - name: Compare Screenshot To Preview
        run: npm run storybook:vrt
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
